# Generated by Django 3.1.3 on 2021-02-19 16:23

from django.db import migrations, models

def create_data(apps, schema_editor):
    trade = apps.get_model('trades', 'Trades')
    trade(symbol="ABC", asset="equity", quantity="0", buy_price="0", sell_price="0").save()

class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Purchased At'),
        ),
        migrations.RunPython(create_data),
    ]
